dashboard:
    resource: "@AcmeMovieBundle/Controller/MainController.php"
    type: annotation

movies:
    resource: "@AcmeMovieBundle/Controller/MovieController.php"
    type: annotation

genres:
    resource: "@AcmeMovieBundle/Controller/GenreController.php"
    type: annotation

directors:
    resource: "@AcmeMovieBundle/Controller/DirectorController.php"
    type: annotation

tags:
    resource: "@AcmeMovieBundle/Controller/TagController.php"
    type: annotation

links:
    resource: "@AcmeMovieBundle/Controller/LinkController.php"
    type: annotation

ajax_genre:
    pattern: /ajax_genre
    defaults: { _controller: AcmeMovieBundle:ClassAjax:genre }

ajax_director:
    pattern: /ajax_director
    defaults: { _controller: AcmeMovieBundle:ClassAjax:director }

ajax_tag:
    pattern: /ajax_tag
    defaults: { _controller: AcmeMovieBundle:ClassAjax:tag }

ajax_link:
    pattern: /ajax_link
    defaults: { _controller: AcmeMovieBundle:ClassAjax:link }

ajax_movie:
    pattern: /ajax_movie
    defaults: { _controller: AcmeMovieBundle:ClassAjax:movie }