parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: %database.name%
    database_user: %database.user%
    database_password: %database.password%
    database_socket: %database.socket%
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b18412e534180bcd797ce7d6bc05af7d
    database_path: null
