parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: 3306
  database_name: movies
  database_user: movies
  database_password: movies
  mailer_transport: smtp
  mailer_host: localhost
  mailer_user: null
  mailer_password: null
  locale: en
  secret: ee71517c5016eb25c8cc5108625f5d622